### ISSUE TITLE
[Meta Issue] Unit tests - List of functions

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-protocol-v3#59]
**Description**
---
Since code coverage is not yet implemented, we need to ensure that each function is tested. Functions in **bold** require additional attention and more thorough testing.

**Functions**
---
**vintage.cairo**:
- [x] get_carbon_vintage
- [x] get_project_carbon
- [x] set_project_carbon
- [x] get_cc_vintages
- [x] get_initial_cc_supply
- [x] get_cc_decimals
- [x] **share_to_cc**
- [x] **cc_to_share**
- [x] update_vintage_status
- [x] **rebase_vintage**
- [x] **set_vintages**
- [ ] get_num_vintages

**offset_handler.cairo**:
- [x] **retire_carbon_credits**
- [x] **retire_list_carbon_credits**
- [ ] get_pending_retirement
- [ ] get_carbon_retired

**booking.cairo**

**mint.cairo**:
- [x] get_carbonable_project_address
- [x] get_payment_token_address
- [x] get_unit_price
- [x] get_available_money_amount
- [x] get_max_money_amount
- [x] get_min_money_amount_per_tx
- [x] is_public_sale_open
- [x] is_sold_out
- [x] is_canceled
- [x] set_public_sale_open
- [x] set_min_money_amount_per_tx
- [x] set_unit_price
- [ ] cancel_mint
- [x] **withdraw**
- [x] **retrieve_amount**
- [x] **public_buy**

**metadata**
- [ ] uri
- [ ] get_provider
- [ ] set_provider
- [ ] get_uri
- [ ] set_uri

**project.cairo**:
- [x] mint
- [x] offset
- [x] batch_mint
- [x] offset
- [ ] set_uri
- [x] decimals
- [x] **balance_of**
- [ ] **balance_of_batch**
- [x] shares_of
- [x] **safe_transfer_from**
- [ ] **safe_batch_transfer_from**
- [x] is_approved_for_all
- [x] set_approval_for_all
- [ ] grant_minter_role
- [ ] revoke_minter_role
- [ ] grant_offsetter_role
- [ ] revoke_offsetter_role
- [ ] only_owner

**Acceptance Criteria**
---

- [x] Verify the feature isn't already tested
- [x] Tests should be written in tests folder, and use tests_lib.cairo to avoid redundancy.
- [x] For more complex features, write integration tests including edge cases.
